version: '3.7'

services:
  eventstore:
    container_name: event-store
    image: eventstore/eventstore:21.2.0-buster-slim
    command: --insecure
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
        test:
            [
            "CMD-SHELL",
            "curl --fail http://localhost:9200 || exit 1",
            ]
        interval: 10s
        timeout: 10s
        retries: 120
  issuetracker-api:
    build:
       context: ../
       dockerfile: src/IssueTracker.Api/Dockerfile
    depends_on:
        elasticsearch:
          condition: service_healthy
        eventstore:
          condition: service_healthy      
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5001:80
